import { BrowserWindow, Menu, app, session as electronSession } from "electron";
import { pathToFileURL } from "node:url";
import path from "node:path";

import iconPath from "../../build/icon.png?asset";
import { setReadyHandler, setSignedOutHandler } from "./auth";
import { emit, onSessionEvent } from "./bus";
import { setNotifyWindow } from "./notify";
import { registerIpc, setCliAgent, setCliFolder, setTrusted } from "./ipc";
import { initSession, resetSession, teardownSession } from "./session";
import { loadSettings, updateSettings } from "./settings";
import { runSmoke } from "./smoke";
import { openHttps } from "./auth";

const argv = process.argv.slice(1);
const smoke = argv.includes("--smoke");
const smokeLogin = argv.includes("--smoke-login");
const argValue = (name: string): string | null => {
  const hit = argv.find((a) => a.startsWith(`${name}=`));
  return hit ? hit.slice(name.length + 1) : null;
};
// Without an explicit AppUserModelID Windows shows no toast for an unpackaged app.
app.setAppUserModelId("com.mantu.dustm.desktop");
const isDev = !app.isPackaged && !!process.env["ELECTRON_RENDERER_URL"];

if (!smoke && !app.requestSingleInstanceLock()) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

async function createWindow(): Promise<BrowserWindow> {
  const settings = await loadSettings();
  const bounds = settings.windowBounds;

  const win = new BrowserWindow({
    width: bounds?.width ?? 1440,
    height: bounds?.height ?? 900,
    x: bounds?.x,
    y: bounds?.y,
    minWidth: 920,
    minHeight: 620,
    show: !smoke,
    backgroundColor: "#161616",
    title: "dustm",
    // The CLI logo, generated by scripts/gen-icons.mjs.
    icon: iconPath,
    // The mockup draws its own title bar; native window controls overlay it.
    titleBarStyle: "hidden",
    titleBarOverlay: { color: "#0F0F0F", symbolColor: "#E2C1FF", height: 46 },
    webPreferences: {
      preload: path.join(__dirname, "../preload/index.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
      spellcheck: false,
      // Notification sounds are played by the page while the window is hidden or unfocused.
      autoplayPolicy: "no-user-gesture-required",
      devTools: isDev,
    },
  });

  const consoleProblems: string[] = [];
  win.webContents.on("console-message", (event) => {
    // Level "error"/"warning" covers CSP violations and failed loads.
    if (event.level === "error" || event.level === "warning") {
      consoleProblems.push(`${event.level}: ${event.message}`.slice(0, 300));
    }
  });

  win.webContents.setWindowOpenHandler(({ url }) => {
    void openHttps(url);
    return { action: "deny" };
  });
  win.webContents.on("will-navigate", (event) => event.preventDefault());

  let prefix: string;
  if (isDev) {
    const url = process.env["ELECTRON_RENDERER_URL"] as string;
    prefix = new URL(url).origin;
    void win.loadURL(url);
  } else {
    const file = path.join(__dirname, "../renderer/index.html");
    prefix = pathToFileURL(file).toString();
    void win.loadFile(file);
  }
  setTrusted(win, prefix);
  setNotifyWindow(win);

  win.on("close", () => {
    const b = win.getNormalBounds();
    void updateSettings({
      windowBounds: { width: b.width, height: b.height, x: b.x, y: b.y },
    });
  });
  win.on("closed", () => {
    mainWindow = null;
  });

  if (isDev) {
    win.webContents.on("before-input-event", (_e, input) => {
      if (input.key === "F12" && input.type === "keyDown") {
        win.webContents.toggleDevTools();
      }
    });
  }

  if (smoke) {
    void runSmoke(
      win,
      { login: smokeLogin, chat: argValue("--smoke-chat"),
        shot: argValue("--smoke-shot"),
        demo: argValue("--smoke-demo"),
        dup: argv.includes("--smoke-dup"),
        profileLoad: argv.includes("--smoke-profile-load"),
        commands: argv.includes("--smoke-commands"),
        attach: argValue("--smoke-attach"),
        btw: argValue("--smoke-btw"),
        escape: argv.includes("--smoke-escape"),
        audit: argv.includes("--smoke-audit"),
        multi: argv.includes("--smoke-multi"),
        deleteProbe: argv.includes("--smoke-delete-probe"),
        out: argValue("--smoke-out") },
      consoleProblems
    );
  }
  return win;
}

void app.whenReady().then(async () => {
  // Deny every permission request (camera, notifications, clipboard-read...).
  electronSession.defaultSession.setPermissionRequestHandler((_wc, _p, cb) =>
    cb(false)
  );
  electronSession.defaultSession.setPermissionCheckHandler(() => false);

  Menu.setApplicationMenu(
    process.platform === "darwin"
      ? Menu.buildFromTemplate([
          { role: "appMenu" },
          { role: "editMenu" },
          { role: "windowMenu" },
        ])
      : null
  );

  registerIpc();
  setCliFolder(argValue("--folder"));
  setCliAgent(argValue("--agent"));

  // A fresh sign-in (or a switch of workspace) starts a clean session.
  setReadyHandler(() => {
    resetSession();
    void initSession().then(() => emit({ type: "conversations-changed" }));
  });
  setSignedOutHandler(() => teardownSession());

  onSessionEvent((event) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send("dustm:event", event);
    }
  });

  mainWindow = await createWindow();
});

app.on("second-instance", () => {
  if (mainWindow) {
    if (mainWindow.isMinimized()) {
      mainWindow.restore();
    }
    mainWindow.focus();
  }
});

app.on("window-all-closed", () => {
  app.quit();
});
