/** Notification sounds (generated by scripts/gen-sounds.mjs). Pure data. */
export const SOUND_IDS = ["none", "chime", "ping", "two-tone", "mantu"] as const;
export type SoundId = (typeof SOUND_IDS)[number];

export const SOUND_LABELS: Record<SoundId, string> = {
  none: "No sound",
  chime: "Chime",
  ping: "Soft ping",
  "two-tone": "Two-tone",
  mantu: "Mantu signature",
};

export function isSoundId(v: unknown): v is SoundId {
  return typeof v === "string" && (SOUND_IDS as readonly string[]).includes(v);
}
